"""inital db version

Revision ID: 78ef5d4ca8e5
Revises: 
Create Date: 2024-05-09 18:33:16.444899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ef5d4ca8e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(precision=10), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('broker', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('num_shares', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(precision=10), nullable=True),
    sa.Column('total', sa.Float(precision=10), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('wallet',
    sa.Column('wallet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('average_price', sa.Float(precision=10), nullable=True),
    sa.Column('number_of_shares', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Float(precision=10), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    op.drop_table('transaction')
    op.drop_table('stock')
    # ### end Alembic commands ###
