"""transaction_wallet_tables

Revision ID: f48860e5c745
Revises: 245fee88461b
Create Date: 2022-08-04 17:33:12.428554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48860e5c745'
down_revision = '245fee88461b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('average_price', sa.Float(precision=10), nullable=True),
    sa.Column('number_of_shares', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Float(precision=10), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['stock.code'], ),
    sa.PrimaryKeyConstraint('wallet_id', 'code')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('broker', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('num_shares', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(precision=10), nullable=True),
    sa.Column('total', sa.Float(precision=10), nullable=True),
    sa.Column('last_update_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('wallet')
    # ### end Alembic commands ###
